name: ProfilsManagerCore
version: '${project.version}'
main: fr.soraxdubbing.profilsmanagercore.ProfilsManagerCore
authors: [ SoraxDubbing ]
website: https://github.com/Sorax5/ProfilsManagerCore
softdepend:
  - Essentials
  - Vault
  - LuckPerms
description: Plugin permettant le multi-compte sur un serveur.

